org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

maven_group=dev.ftb.mods
mod_id=ftbultimine
archives_base_name=ftb-ultimine
readable_name=FTB Ultimine
mod_author=FTB Team

mod_version=6

minecraft_version=26.2
supported_minecraft_versions=26.2,26.2.1,26.2.2
minecraft_version_range_maven=[26.2,27)
minecraft_version_range_semver=>=26.2.0

neoforge_version=26.2.0.7-beta
neoforge_version_range=[26.2.0.7-beta,27)
neoforge_loader_version=4

fabric_loader_version=0.19.3
fabric_api_version=0.154.2+26.2
fabric_api_version_range=>=0.144.0+26.2

ftb_library_version=26.2.0.8-SNAPSHOT
ftb_library_version_range_semver=>=26.2.0.8
ftb_library_version_range_maven=[26.2.0.8,27)
ftb_ranks_version=26.2.0.3-SNAPSHOT
ftb_ranks_version_range_semver=>=26.2.0.3
ftb_ranks_version_range_maven=[26.2.0.3,27)
ftb_ez_crystals_version=26.2.0.2
accelerated_decay_version_semver_break=<26.2.0.1
accelerated_decay_version_range=[26.2.0.1,27)

curseforge_id_forge=386134
curseforge_id_fabric=448231
